### ISSUE TITLE
Got errors on fresh npm install 

### ISSUE THREAD

**Issue by OmSolution** [vinsol-spree-contrib/spree-on-react#16]
Failed to compile.

Error in ./src/connected-intl-provider.jsx
Module not found: ./../translations/app-translations.json in /Users/Apple/RAILS_PROJECTS/spree-on-react/src

 @ ./src/connected-intl-provider.jsx 11:23-73

After running npm run build:langs got following errors

spree-on-react@0.1.0 build:langs /Users/Apple/RAILS_PROJECTS/spree-on-react
> babel-node scripts/translate.js

/Users/Apple/RAILS_PROJECTS/spree-on-react/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing preset: "/Users/Apple/RAILS_PROJECTS/spree-on-react/node_modules/babel-preset-react-app/index.js")
    at Object.<anonymous> (/Users/Apple/RAILS_PROJECTS/spree-on-react/node_modules/babel-preset-react-app/index.js:49:9)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Apple/RAILS_PROJECTS/spree-on-react/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/Apple/RAILS_PROJECTS/spree-on-react/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:296:17

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:langs"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! spree-on-react@0.1.0 build:langs: `babel-node scripts/translate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spree-on-react@0.1.0 build:langs script 'babel-node scripts/translate.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spree-on-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node scripts/translate.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spree-on-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spree-on-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Apple/RAILS_PROJECTS/spree-on-react/npm-debug.log

**Comment by homoluden** [comment]
I think I managed to resolve the same issue inside Ubuntu 16.04.2 Virtual Image (VBox).

I just did 1. "export NODE_ENV=development" in BASH and 2. "npm run build:langs".
After these steps FE is running ok in Development mode. Didn't test it in Production. Hope it'll work.

PS: @OmSolution MANY THANKS FOR "build:langs"
PS 2: Maybe it will be useful to put the note about NODE_ENV and "build:langs" into README?

**Comment by ShubhamGupta** [comment]
@OmSolution I somehow got unsubscribed from the notifications from this repo, causing the delay in reply. Thanks for reporting the issue. I was able to replicate the issue. I have updated the Readme. Thanks @homoluden for the suggestion.
