### ISSUE TITLE
Server-side-rendering / SEO ?

### ISSUE THREAD

**Issue by Obi-TOB** [vinsol-spree-contrib/spree-on-react#18]
Does your implementation use server-side rendering? 

Or anything comparable to help with SEO?

Many thanks for any infos.

**Comment by ShubhamGupta** [comment]
Hey @Obi-TOB No, this is entirely rendered on the client. Although I am not an expert in SEO, I can confirm that Google does understand the Javascript and is able to treat the pages like the browsers. So, it can index the pages written with client side rendering and also display them properly on search engine results. The same is also true for Bing to some extent. SEO should not really be a blocker for using client rendering. See this: https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

Again, while SEO friendliness is on our roadmap and we'll focus on writing guidelines and make the app generally more indexable, this is not something we have started yet. You can definitely wait for more support on this in about a month. I can plan a release exclusively for this one.
